version: '3'

services:
  db:
    image: arm64v8/mysql:8.0.34
    container_name: spring-msa-coding-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passowrd
      TZ: Asia/Seoul
      command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
