spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db;MODE=MySQL;
    username: sa
    password:
    hikari:
      pool-name: core-db-pool

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
        query.fail_on_pagination_over_collection_fetch: true
    open-in-view: false